version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./mongo-data/:/data/db
    networks:
      - mongodb
      - flaskr
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    networks:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  flaskr:
    build: .
    image: flaskr
    container_name: flaskr
    depends_on: 
      - mongo
    ports:
      - 8080:8080
    networks: 
      - flaskr

networks:
  mongodb:
  flaskr:
